# Generated by Django 6.1.1 on 2026-09-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cuenta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('AHORRO', 'Cuenta ahorro'), ('CORRIENTE', 'Cuenta corriente'), ('VISTA', 'Cuenta vista')], default='vista', max_length=20),
        ),
    ]
