# Generated by Django 6.1.1 on 2026-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_cuenta_estado_alter_cuenta_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
