# Generated by Django 6.1.1 on 2026-09-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_transaccion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='banco_destino',
        ),
    ]
