# Generated by Django 6.1.1 on 2026-09-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('DESACTIVADA', 'Desactivada')], default='ACTIVA', max_length=20),
        ),
    ]
