# Generated by Django 6.1.1 on 2026-09-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cuenta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='estado',
        ),
    ]
